import test from 'node:test';
import assert from 'node:assert/strict';
import {AttendanceApp} from '../assets/app.js';
import {DraftQueue} from '../assets/core.js';
const storage=()=>({map:new Map(),getItem(k){return this.map.get(k)||null;},setItem(k,v){this.map.set(k,v);},removeItem(k){this.map.delete(k);}});
function app(){globalThis.document={addEventListener(){}};globalThis.window={addEventListener(){}};const a=new AttendanceApp();a.render=()=>{};a.toast=()=>{};a.updateSaveState=()=>{};a.state.user={id:'teacher',role:'advisor'};a.queue=new DraftQueue(storage(),'teacher');a.state.attendance={date:'2026-10-01',classroomId:'c1',loadedKey:'2026-10-01:c1',revision:3,students:[{id:'s1'},{id:'s2'}],records:[{studentId:'s1',status:'present',reason:''}],search:''};return a;}
test('failed reload clears old date data and prevents a new-date save',async()=>{const a=app();a.state.attendance.date='2026-10-02';a.api={call:async()=>{throw new Error('offline');}};await assert.rejects(a.loadAttendance());assert.deepEqual(a.state.attendance.records,[]);assert.equal(a.state.attendance.loadedKey,'');assert.throws(()=>a.enqueue('saveAttendance',[{studentId:'s1',status:'present'}]),/ยังโหลดข้อมูล/);});
test('an older room response cannot replace the currently chosen classroom',async()=>{const a=app();let finish;a.api={call:()=>new Promise(resolve=>finish=resolve)};const pending=a.loadAttendance();a.state.attendance.classroomId='c2';a.state.attendance.loadedKey='2026-10-01:c2';a.state.attendance.records=[{studentId:'s9',status:'late'}];finish({students:[{studentId:'s1'}],records:[{studentId:'s1',status:'absent'}],revision:7});await pending;assert.equal(a.state.attendance.records[0].studentId,'s9');assert.equal(a.state.attendance.loadedKey,'2026-10-01:c2');});
test('typing a reason then quickly marking another student retains the reason',async()=>{const a=app();a.sync=async()=>{};a.input({target:{dataset:{reasonId:'s1'},value:'ลาป่วย'}});await a.mark('s2','late');assert.equal(a.state.attendance.records.find(r=>r.studentId==='s1').reason,'ลาป่วย');assert.equal(a.queue.items[0].payload.records[0].reason,'ลาป่วย');assert.equal(a.queue.items.length,2);assert.equal(a.reasonTimers.size,0);});
test('in-flight acknowledgements only remove drafts from the original account',async()=>{const a=app();a.enqueue('saveAttendance',[{studentId:'s1',status:'present'}]);const original=a.queue;let finish;a.api={call:()=>new Promise(resolve=>finish=resolve)};const pending=a.sync();a.queue=new DraftQueue(storage(),'another-teacher');a.state.user=null;finish({revision:4});await pending;assert.equal(original.items.length,0);assert.equal(a.queue.items.length,0);assert.equal(a.syncing,false);});
test('audit dialog exposes coordinates from the backend location wrapper',async()=>{const a=app();a.api={call:async()=>[{timestamp:'2026-10-01T01:00:00Z',actorName:'ครู',action:'save_attendance',location:{location:{latitude:6.1234,longitude:100.9876,accuracy:17},locationError:''}}]};let captured;a.modal=async options=>{captured=options;return {};};await a.showLogs();assert.ok(captured.html.includes('6.1234, 100.9876'));assert.ok(captured.html.includes('17 เมตร'));});
test('public guide loads without querying private data; protected pages still require login',async()=>{const a=app();a.state.user=null;globalThis.history={replaceState(){}};document.body={classList:{remove(){}}};a.api={call:async()=>{throw new Error('Public help must not query backend');}};await a.navigate('guide');assert.equal(a.state.route,'guide');assert.equal(a.state.loading,false);await a.navigate('attendance');assert.equal(a.state.route,'login');});
